spring:
  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/board?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.gon.test.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  siteName: boardTest
  siteMainUri: http://localhost:8090/usr/home/main
  siteLoginUri: http://localhost:8090/usr/member/login
  emailFrom: no-reply@localhost
  emailFromName: boardTest
  logging:
    dir: log
    level: info

---

spring:
  profiles: local
server:
  port: 8090
  
---

